blueprint:
  name: Styrbar Light Remote Control with Multiple Devices and Persistence
  description: Control light(s) on multiple devices with a remote control, switching between them and showing a visual indicator.
  domain: automation
  input:
    remote:
      name: Remote Control
      description: The remote control device (e.g., a button or sensor).
      selector:
        entity:
          domain: remote
    lights:
      name: Lights
      description: List of lights to toggle
      selector:
        entity:
          domain: light
      multiple: true
    toggle_action:
      name: Toggle Action
      description: Action to perform when button is pressed (e.g., turn on, turn off).
      default: toggle
      selector:
        action: {}

trigger:
  platform: state
  entity_id: !input remote
  to: 'on'  # Triggering on button press (adjust as necessary for your remote control)
  
action:
  - variables:
      light_list: !input lights
      current_light: "{{ states('input_select.current_light') }}"
  - choose:
      # When the button is pressed, we toggle the current light.
      - conditions:
          - condition: state
            entity_id: "{{ current_light }}"
            state: 'on'
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ current_light }}"
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness: 255  # Full brightness when active
              color_name: 'blue'  # Change color to blue to show it's the active light
      - conditions:
          - condition: state
            entity_id: "{{ current_light }}"
            state: 'off'
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness: 255  # Full brightness when activated
              color_name: 'yellow'  # Yellow for "active" indicator
  - service: input_select.select_next
    target:
      entity_id: input_select.current_light

input_select:
  current_light:
    name: Current Light
    options:
      - light.luz_sala
      - light.luz_quarto
      - light.luz_cozinha
    initial: light.luz_sala
    icon: mdi:lightbulb

# Ensuring persistence of the current light
persistent_notification:
  title: "Light Control Active"
  message: "Current active light: {{ states('input_select.current_light') }}"

